### ISSUE TITLE
Support target folder other than .

### ISSUE THREAD

**Issue by nikku** [assemble/grunt-assemble-sitemap#19]
We generate the results of our webside to the directory `dist/` and later copy the contents of that directory to the root of a web server. 

That means the effective url of a `index.html` file located in the `dist` directory is `http://my.site/index.html` rather than `http://my.site/dist/index.html`.

Looking into the generated sitemap.xml, I see that the `dist/` part is written into the `<loc />` tag.
Is there an option to strip that part from the location tag?

**Comment by brunobatista** [comment]
In my case my URL show `http://domain.com/.tmp/admin/changelog.html`, if have a way to strip `.tmp/` will be nicer. 

My task:

```js
    // Generate HTML files from handlebars source
    assemble: {
      options: {
        data: [
          '<%= config.app %>/templates/data/*.json',
          'package.json'
        ],
        layoutdir: '<%= config.app %>/templates/layouts',
        layout: 'page.hbs',
        partials: ['<%= config.app %>/templates/partials/**/*.hbs'],
        flatten: true
      },
      server: {
        options: {
          plugins: ['assemble-middleware-sitemap'],
          sitemap: {
            dest: '<%= config.app %>',
            exclusions: []
          }
        },
        files: [{
          expand: true,
          cwd: '<%= config.app %>/templates/pages/',
          src: ['{,*/}*.hbs'],
          dest: '.tmp',
          ext: '.html'
        }]
      }
    },
```
