### ISSUE TITLE
Multi-target sitemap

### ISSUE THREAD

**Issue by oncletom** [assemble/grunt-assemble-sitemap#31]
Hello,

at the moment I run the command `grunt assemble` which has many targets.
However only the last target remains in the sitemap.

Is this how the plugin is intended to work? 

I suppose you should create a writeStream when grunt is about run, and you write every time you encounter a page, then you close the stream when grunt ends its work.

**Comment by siryan2** [comment]
+1

**Comment by AurelioDeRosa** [comment]
This issue is crucial for this plugin to be really useful. Is there any plan to implement the fix for it?

**Comment by kdekooter** [comment]
+1

**Comment by kdekooter** [comment]
a few words motivating the closing of the issue would be nice

**Comment by thom4parisot** [comment]
Just doing some issues triaging at the moment – I'm not using assemble anymore and I think the issue corresponds to a niche need.
