### ISSUE TITLE
Moving to `grunt-assemble-sitemap`

### ISSUE THREAD

**Issue by doowb** [assemble/grunt-assemble-sitemap#36]
@hariadi we'd like to move this code to `grunt-assemble-sitemap` and deprecating `assemble-middleware-sitemap` on npm. Let me know if you have any issues/questions/comments about this and we can discuss it.

There are some outstanding PRs and issues that may be resolved before moving. Let me know if you'd like to handle any of them.

**Comment by hariadi** [comment]
:+1: 

As for "compression" and "multi-target sitemap" issue, I think we can handle after move to `grunt-assemble-sitemap`

**Comment by doowb** [comment]
Done.

- [x] tagged code snapshot before moving to `grunt-assemble-sitemap`
- [x] renamed and updated docs/gruntfile to `grunt-assemble-sitemap`
- [x] published `grunt-assemble-sitemap` to npm (added owners)
- [x] renamed repository to `grunt-assemble-sitemap`
